OVERVIEW = {"id": "00-sopy-overview", "tag": "00", "title_en": "SOPY in 60 seconds", "title_ar": "SOPY في دقيقة",
 "scenes": [
   ("hook", {"big_en": "Your restaurant's SOPs, on every phone.", "big_ar": "إجراءات مطعمك، على كل هاتف."},
    "Your restaurant's SOPs, on every phone.",
    "إِجْرَاءَاتُ مَطْعَمِكَ، عَلَى كُلِّ هَاتِف."),
   ("binder", {},
    "Paper SOPs get lost, skipped, and never checked.",
    "الْوَرَقُ يَضِيعُ وَيُهْمَلُ وَلَا يُرَاجَع."),
   ("phone:home", {},
    "With SOPY, every checklist and daily report lives on your team's phones.",
    "مَعَ سُو بِي، كُلُّ قَوَائِمِ الْفَحْصِ وَالتَّقَارِيرِ عَلَى هَوَاتِفِ فَرِيقِك."),
   ("phone:tempalert", {},
    "A fridge goes out of range? You know instantly.",
    "ثَلَّاجَةٌ خَارِجَ النِّطَاقِ الْآمِن؟ تَعْرِفُ فَوْرًا."),
   ("phone:critical", {},
    "QC visits score live, and a critical fail flags an incident.",
    "زِيَارَاتُ الْجَوْدَةِ تُقَيَّمُ لَحْظِيًّا، وَالْمُخَالَفَةُ الْحَرِجَةُ تُسَجِّلُ حَادِثَة."),
   ("phone:stamp", {},
    "Photo proof, stamped with the time and location.",
    "صُوَرٌ حَيَّةٌ كَدَلِيل، بِالْوَقْتِ وَالْمَوْقِع."),
   ("phone:kpi", {},
    "And one dashboard shows which branch needs you first.",
    "وَلَوْحَةٌ وَاحِدَةٌ تُرِيكَ أَيَّ فَرْعٍ يَحْتَاجُكَ أَوَّلًا."),
   ("cta", {}, "SOPY. Your SOP manual, on every shift.",
    "سُو بِي. دَلِيلُ إِجْرَاءَاتِ التَّشْغِيلِ مَعَكَ فِي كُلِّ وَرْدِيَّة."),
 ]}
