# SOPY tutorial video scripts — EN + AR (Arabic VO is diacritized MSA for TTS;
# on-screen Arabic captions are the same text with diacritics stripped).
# Each scene: (template, params, EN caption/VO, AR VO). "vo_en" may differ from
# caption only for pronunciation ("Soppy").

VIDEOS = [
 {"id": "01-what-is-sopy", "tag": "01", "title_en": "What is SOPY?", "title_ar": "ما هو SOPY؟",
  "scenes": [
   ("hook", {"big_en": "Still running your restaurant on paper SOPs?", "big_ar": "ما زلت تدير مطعمك بملفات ورقية؟"},
    "Still running your restaurant on paper SOP binders?",
    "هَلْ مَا زِلْتَ تُدِيرُ مَطْعَمَكَ بِمَلَفَّاتٍ وَرَقِيَّة؟"),
   ("binder", {},
    "Paper gets lost, skipped, and never checked twice.",
    "الْوَرَقُ يَضِيعُ، وَيُهْمَلُ، وَلَا يُرَاجَعُ مَرَّتَيْن."),
   ("phone:home", {},
    "SOPY puts every checklist, log, and sign-off on the phone your team already carries.",
    "سُو بِي يَضَعُ كُلَّ قَائِمَةِ فَحْصٍ، وَكُلَّ سِجِلٍّ وَاعْتِمَاد، عَلَى الْهَاتِفِ الَّذِي يَحْمِلُهُ فَرِيقُكَ أَصْلًا."),
   ("phone:rings", {},
    "You see compliance in real time, for every branch, not after an inspection finds the gap.",
    "وَتَرَى مُسْتَوَى الِالْتِزَامِ لَحْظِيًّا فِي كُلِّ فَرْع، لَا بَعْدَ أَنْ يَكْتَشِفَ التَّفْتِيشُ الثَّغْرَة."),
   ("bullets", {"items_en": ["Safer food", "Faster training", "Same quality, every shift", "Owner freedom"],
                "items_ar": ["طعام أكثر أمانًا", "تدريب أسرع", "نفس الجودة في كل وردية", "حرية للمالك"]},
    "Safer food. Faster training. The same quality on every shift.",
    "طَعَامٌ أَكْثَرُ أَمَانًا، وَتَدْرِيبٌ أَسْرَع، وَجَوْدَةٌ وَاحِدَةٌ فِي كُلِّ وَرْدِيَّة."),
   ("cta", {}, "SOPY. Your SOP manual, on every shift.",
    "سُو بِي. دَلِيلُ إِجْرَاءَاتِ التَّشْغِيلِ مَعَكَ فِي كُلِّ وَرْدِيَّة."),
  ]},
 {"id": "02-setup-in-minutes", "tag": "02", "title_en": "Set up in minutes", "title_ar": "جاهز في دقائق",
  "scenes": [
   ("hook", {"big_en": "Your whole restaurant, set up in minutes.", "big_ar": "مطعمك بالكامل جاهز في دقائق."},
    "Set up your whole restaurant in minutes.",
    "جَهِّزْ مَطْعَمَكَ بِالْكَامِلِ فِي دَقَائِق."),
   ("phone:stores", {},
    "Add your branches, and pick each city from a smart list.",
    "أَضِفْ فُرُوعَكَ، وَاخْتَرِ الْمَدِينَةَ مِنْ قَائِمَةٍ ذَكِيَّة."),
   ("phone:roles", {},
    "Choose roles: owner, operations manager, area manager, store manager, and employee. Everyone sees exactly what they need.",
    "حَدِّدِ الْأَدْوَار: الْمَالِك، وَمُدِيرُ الْعَمَلِيَّات، وَمُدِيرُ الْمِنْطَقَة، وَمُدِيرُ الْفَرْع، وَالْمُوَظَّف. كُلُّ شَخْصٍ يَرَى مَا يَحْتَاجُهُ فَقَط."),
   ("phone:invite", {},
    "Invite your team with one link. They open it, and they're in.",
    "اُدْعُ فَرِيقَكَ بِرَابِطٍ وَاحِد. يَفْتَحُونَهُ، وَيَبْدَؤُونَ الْعَمَلَ فَوْرًا."),
   ("phone:pricing", {},
    "Pay only for what you use. The price per branch and per user drops as you grow.",
    "اِدْفَعْ فَقَطْ مُقَابِلَ مَا تَسْتَخْدِمُه. وَسِعْرُ الْفَرْعِ وَالْمُسْتَخْدِمِ يَقِلُّ كُلَّمَا كَبُرْت."),
   ("cta", {}, "SOPY. Your SOP manual, on every shift.",
    "سُو بِي. دَلِيلُ إِجْرَاءَاتِ التَّشْغِيلِ مَعَكَ فِي كُلِّ وَرْدِيَّة."),
  ]},
 {"id": "03-kitchen-bar-reports", "tag": "03", "title_en": "Kitchen & bar daily reports", "title_ar": "تقارير المطبخ والبار",
  "scenes": [
   ("hook", {"big_en": "Your kitchen report. Done right, every shift.", "big_ar": "تقرير المطبخ. صحيح في كل وردية."},
    "Your kitchen report, done right, every single shift.",
    "تَقْرِيرُ الْمَطْبَخِ الْيَوْمِيّ، صَحِيحٌ فِي كُلِّ وَرْدِيَّة."),
   ("phone:temps", {},
    "Log fridge, freezer, and hot-holding temperatures at the start, middle, and end of the shift.",
    "سَجِّلْ حَرَارَةَ الثَّلَّاجَة، وَالْمُجَمِّد، وَحِفْظِ الطَّعَامِ السَّاخِن، فِي بِدَايَةِ الْوَرْدِيَّةِ وَمُنْتَصَفِهَا وَنِهَايَتِهَا."),
   ("phone:tempalert", {},
    "Out of the safe range? SOPY flags it in red, instantly, before it becomes a food-safety problem.",
    "خَارِجَ النِّطَاقِ الْآمِن؟ سُو بِي يُنَبِّهُكَ بِاللَّوْنِ الْأَحْمَرِ فَوْرًا، قَبْلَ أَنْ تُصْبِحَ مُشْكِلَةً فِي سَلَامَةِ الْغِذَاء."),
   ("phone:checklist", {},
    "Tick off opening and closing tasks, the same way on every shift, then sign off.",
    "أَنْجِزْ مَهَامَّ الِافْتِتَاحِ وَالْإِغْلَاقِ بِنَفْسِ الطَّرِيقَةِ فِي كُلِّ وَرْدِيَّة، ثُمَّ اعْتَمِدِ التَّقْرِير."),
   ("phone:waste", {},
    "Record waste with a reason, so you can see exactly where the money leaks.",
    "سَجِّلِ الْهَالِكَ مَعَ السَّبَب، لِتَعْرِفَ أَيْنَ تَتَسَرَّبُ الْأَمْوَال."),
   ("phone:bar", {},
    "The bar and beverage report works the same way, with its own ranges and checks.",
    "وَتَقْرِيرُ الْبَارِ وَالْمَشْرُوبَاتِ يَعْمَلُ بِنَفْسِ الطَّرِيقَة، بِنِطَاقَاتِهِ وَفُحُوصَاتِهِ الْخَاصَّة."),
   ("cta", {}, "SOPY. Your SOP manual, on every shift.",
    "سُو بِي. دَلِيلُ إِجْرَاءَاتِ التَّشْغِيلِ مَعَكَ فِي كُلِّ وَرْدِيَّة."),
  ]},
 {"id": "04-qc-visits-scoring", "tag": "04", "title_en": "QC visits & live scoring", "title_ar": "زيارات الجودة والتقييم",
  "scenes": [
   ("hook", {"big_en": "Know your score before the inspector does.", "big_ar": "اعرف درجتك قبل أن يعرفها المفتش."},
    "Know your quality score before the inspector does.",
    "اِعْرِفْ دَرَجَةَ الْجَوْدَةِ قَبْلَ أَنْ يَعْرِفَهَا الْمُفَتِّش."),
   ("phone:qc", {},
    "Walk the branch with the daily QC checklist: over one hundred points, section by section.",
    "تَجَوَّلْ فِي الْفَرْعِ بِقَائِمَةِ فَحْصِ الْجَوْدَةِ الْيَوْمِيَّة: أَكْثَرُ مِنْ مِئَةِ نُقْطَة، قِسْمًا بَعْدَ قِسْم."),
   ("phone:score", {},
    "Mark each point OK or Issue, and watch the score update live.",
    "حَدِّدْ كُلَّ نُقْطَة: سَلِيمَةٌ أَمْ بِهَا مُشْكِلَة، وَشَاهِدِ الدَّرَجَةَ تَتَغَيَّرُ لَحْظِيًّا."),
   ("thresholds", {},
    "Ninety-five percent or more is green. Eighty-five to ninety-four is amber. Below that is red.",
    "خَمْسَةٌ وَتِسْعُونَ فِي الْمِئَةِ فَأَكْثَر: أَخْضَر. مِنْ خَمْسَةٍ وَثَمَانِينَ إِلَى أَرْبَعَةٍ وَتِسْعِين: بُرْتُقَالِيّ. وَأَقَلُّ مِنْ ذَلِكَ: أَحْمَر."),
   ("phone:critical", {},
    "One critical failure turns the report red and flags an incident, automatically.",
    "وَأَيُّ مُخَالَفَةٍ حَرِجَةٍ وَاحِدَة، تُحَوِّلُ التَّقْرِيرَ إِلَى الْأَحْمَر، وَتُسَجِّلُ حَادِثَةً تِلْقَائِيًّا."),
   ("bullets", {"items_en": ["Daily QC walk", "Weekly audit", "Monthly audit", "Quarterly audit"],
                "items_ar": ["جولة الجودة اليومية", "تدقيق أسبوعي", "تدقيق شهري", "تدقيق ربع سنوي"]},
    "Weekly, monthly, and quarterly audits follow the same system.",
    "وَالتَّدْقِيقُ الْأُسْبُوعِيُّ وَالشَّهْرِيُّ وَالرُّبْعُ سَنَوِيّ، يَتْبَعُ نَفْسَ النِّظَام."),
   ("cta", {}, "SOPY. Your SOP manual, on every shift.",
    "سُو بِي. دَلِيلُ إِجْرَاءَاتِ التَّشْغِيلِ مَعَكَ فِي كُلِّ وَرْدِيَّة."),
  ]},
 {"id": "05-camera-evidence", "tag": "05", "title_en": "Photo evidence you can trust", "title_ar": "دليل مصوّر موثوق",
  "scenes": [
   ("hook", {"big_en": "“It was clean, I promise.”\nNow you can see it.", "big_ar": "«كان نظيفًا، أؤكد لك».\nالآن يمكنك أن ترى بنفسك."},
    "“It was clean, I promise.” Now you can see it for yourself.",
    "كَانَ نَظِيفًا، أُؤَكِّدُ لَك. الْآنَ يُمْكِنُكَ أَنْ تَرَى بِنَفْسِك."),
   ("phone:camera", {},
    "When a check needs proof, your team takes a live photo right inside SOPY.",
    "عِنْدَمَا يَحْتَاجُ الْفَحْصُ إِلَى دَلِيل، يَلْتَقِطُ فَرِيقُكَ صُورَةً حَيَّةً مِنْ دَاخِلِ سُو بِي."),
   ("phone:stamp", {},
    "Every photo is saved with the time and location, attached to the exact checklist item.",
    "كُلُّ صُورَةٍ تُحْفَظُ بِالْوَقْتِ وَالْمَوْقِع، مُرْتَبِطَةً بِبَنْدِ الْفَحْصِ نَفْسِه."),
   ("phone:nogallery", {},
    "Camera only. No uploads from the gallery, so no old photos and no shortcuts.",
    "الْكَامِيرَا فَقَط. لَا رَفْعَ مِنْ مَعْرِضِ الصُّوَر، فَلَا صُوَرَ قَدِيمَة، وَلَا تَحَايُل."),
   ("bullets", {"items_en": ["Live photo only", "Time + GPS stamp", "Linked to the checklist item", "Visible from anywhere"],
                "items_ar": ["صورة حية فقط", "ختم الوقت والموقع", "مرتبطة ببند الفحص", "تراها من أي مكان"]},
    "Honest evidence you can trust, from every branch, even when you're not there.",
    "دَلِيلٌ صَادِقٌ تَثِقُ بِهِ مِنْ كُلِّ فَرْع، حَتَّى وَأَنْتَ غَيْرُ مَوْجُود."),
   ("cta", {}, "SOPY. Your SOP manual, on every shift.",
    "سُو بِي. دَلِيلُ إِجْرَاءَاتِ التَّشْغِيلِ مَعَكَ فِي كُلِّ وَرْدِيَّة."),
  ]},
 {"id": "06-manager-dashboard-builder", "tag": "06", "title_en": "The manager's view", "title_ar": "لوحة المدير",
  "scenes": [
   ("hook", {"big_en": "Run every branch from one screen.", "big_ar": "أدر كل فروعك من شاشة واحدة."},
    "Run every branch from one screen.",
    "أَدِرْ كُلَّ فُرُوعِكَ مِنْ شَاشَةٍ وَاحِدَة."),
   ("phone:kpi", {},
    "The KPI dashboard compares compliance across branches, so you know where to act first.",
    "لَوْحَةُ مُؤَشِّرَاتِ الْأَدَاءِ تُقَارِنُ الِالْتِزَامَ بَيْنَ الْفُرُوع، لِتَعْرِفَ أَيْنَ تَتَحَرَّكُ أَوَّلًا."),
   ("phone:builder", {},
    "Build your own checklists from a ready library: HACCP, ISO 22000, QC audits, and twenty SOPs.",
    "اِبْنِ قَوَائِمَ الْفَحْصِ الْخَاصَّةَ بِكَ، مِنْ مَكْتَبَةٍ جَاهِزَة: مَعَايِيرُ الْهَاسَب وَالْأَيْزُو، وَتَدْقِيقُ الْجَوْدَة، وَعِشْرُونَ إِجْرَاءَ تَشْغِيل."),
   ("phone:builderselect", {},
    "Show critical items only, select them all, and assign them to your team.",
    "اِعْرِضِ الْبُنُودَ الْحَرِجَةَ فَقَط، اِخْتَرْهَا كُلَّهَا، وَعَيِّنْهَا لِفَرِيقِك."),
   ("phone:reports", {},
    "Every report is saved and shareable, so you can finally take a day off.",
    "كُلُّ تَقْرِيرٍ مَحْفُوظٌ وَقَابِلٌ لِلْمُشَارَكَة، فَتَسْتَطِيعُ أَخِيرًا أَنْ تَأْخُذَ يَوْمَ رَاحَة."),
   ("cta", {}, "SOPY. Your SOP manual, on every shift.",
    "سُو بِي. دَلِيلُ إِجْرَاءَاتِ التَّشْغِيلِ مَعَكَ فِي كُلِّ وَرْدِيَّة."),
  ]},
]

import re
HARAKAT = re.compile(r'[ً-ْٰ]')
def strip_ar(s):
    return HARAKAT.sub('', s).replace('سو بي', 'SOPY')
def vo_en(s):
    return s.replace('SOPY', 'Soppy').replace('HACCP', 'H.A.C.C.P.').replace('ISO 22000', 'I.S.O. twenty-two thousand').replace('KPI', 'K.P.I.').replace('QC', 'Q.C.')
